name: Github_Actions_Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}} # Adjust the Node.js version as per your project's requirements

      - name: Install NPM  dependencies
        run: npm install

        # This step updates the package-lock.json to match the latest package.json
        # Ensure that your package.json is up to date with the desired dependencies

      - name: Run tests
        run: npm test
