name: 
  First workflow

on: 
    push

jobs: 
    job1:
      runs-on: ubuntu-latest
      steps: 
        - name: run checkout
          uses: actions/checkout@v2
        - name: say hello
          run: echo "hello world"
          shell: bash








