name: 
  First workflow

on: 
    push

jobs: 
    job1:
      runs-on: ubuntu-latest
      steps: 
        - name: run checkout
          uses: actions/checkout@v2

        - name: say hello
          run: echo "hello world"
          shell: bash

        - name: installing dependencies
          run: npm install

        - name: run tests
          run: npm run test
          
        - name: merge a branch
          run: 
            git switch main
            git merge add-feature
            git add *
            git commit -m "merging add-feature into main branch.."
            git push







